apiVersion: v1
kind: Service
metadata:
  name: rapp-tcn-service
  namespace: rapp
spec:
  type: ClusterIP
  selector:
    app: rapp-tcn
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8005
